theme = "blowfish"
# baseURL = "https://qharo.github.io"
defaultContentLanguage = "en"

# Add these recommended settings
languageCode = "en"

[pagination]
pagerSize = 10

[params]
  defaultFeaturedImage = "img/defaultFeatured.jpg"  #